# Generated by Django 6.0.3 on 2026-06-26 06:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('dosage', models.CharField(help_text='e.g. 500mg', max_length=100)),
                ('instructions', models.TextField(blank=True, help_text='e.g. Take with food. Avoid alcohol.')),
                ('frequency', models.PositiveIntegerField(help_text='Number of times per day or interval in hours')),
                ('frequency_unit', models.CharField(choices=[('daily', 'Times per day'), ('hours', 'Every N hours')], default='daily', max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for ongoing medications', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('prescribed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescriptions_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DosageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scheduled_time', models.DateTimeField()),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('taken', 'Taken'), ('missed', 'Missed'), ('skipped', 'Skipped')], default='taken', max_length=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='patients.medication')),
            ],
            options={
                'db_table': 'dosage_logs',
                'ordering': ['-scheduled_time'],
            },
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('', 'Unknown')], default='', max_length=3)),
                ('national_id', models.CharField(blank=True, max_length=20)),
                ('allergies', models.TextField(blank=True)),
                ('chronic_conditions', models.TextField(blank=True, help_text='e.g. Diabetes Type 2, Hypertension')),
                ('emergency_contact_name', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient_profiles',
            },
        ),
        migrations.AddField(
            model_name='medication',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patientprofile'),
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('lab_result', 'Lab Result'), ('prescription', 'Prescription'), ('surgery', 'Surgery'), ('allergy', 'Allergy'), ('vaccination', 'Vaccination'), ('note', 'General Note')], default='note', max_length=15)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date_of_record', models.DateField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='medical_records/')),
                ('is_private', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='written_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='patients.patientprofile')),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-date_of_record'],
            },
        ),
    ]
